name: aliyun_httpdns_example
description: "Demonstrates how to use the aliyun_httpdns plugin."
publish_to: 'none'

environment:
  sdk: ">=2.18.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  aliyun_httpdns:
    # When depending on this package from a real application you should use:
    #   aliyun_httpdns: ^x.y.z
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  http: ^1.2.0
  http2: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
